// apps/docs/src/app/components/table-of-contents/table-of-contents.component.ts
import { Component, computed, input, signal } from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';

export interface TocItem {
	id: string;
	text: string;
	level: number;
	children: TocItem[];
}

@Component({
	selector: 'fkt-table-of-contents',
	imports: [NgTemplateOutlet],
	templateUrl: './table-of-contents.component.html',
	styleUrl: './table-of-contents.component.scss',
	host: {
		"role": "aside"
	}
})
export class TableOfContentsComponent {
	excludedContainerSelector = input<string>();

	protected readonly tocItems = signal<TocItem[]>([]);
	protected readonly activeIds = signal<string[]>([]);
	protected readonly isVisible = signal(false);

	protected readonly hasItems = computed(() => this.tocItems().length > 0);

	public generate() {
		this.generateTableOfContents();
		this.setupIntersectionObserver();
	}

	private generateTableOfContents() {
		const headings = this.getHeadings();

		const items: TocItem[] = [];
		const stack: TocItem[] = [];

		headings.forEach((heading, index) => {
			const level = parseInt(heading.tagName.charAt(1));
			const text = heading.textContent?.trim() || '';
			const id = heading.id || this.generateId(text, index);

			if (!heading.id) {
				heading.id = id;
			}

			const item: TocItem = {
				id,
				text,
				level,
				children: []
			};

			while (stack.length > 0 && stack[stack.length - 1].level >= level) {
				stack.pop();
			}

			if (stack.length === 0) {
				items.push(item);
			} else {
				stack[stack.length - 1].children.push(item);
			}

			stack.push(item);
		});

		this.tocItems.set(items);
	}

	private getHeadings() {
		const contentElement = document.querySelector('.docs');
		if (!contentElement) {
			return [];
		}

		const headings = Array.from(contentElement.querySelectorAll('h2, h3, h4, h5, h6'));

		return headings.filter(heading => {
			const excludedContainer = this.excludedContainerSelector();

			if (!excludedContainer) return true;

			return !heading.closest(excludedContainer)
		});
	}

	private generateId(text: string, index: number): string {
		const slug = text
			.toLowerCase()
			.replace(/[^\w\s-]/g, '')
			.replace(/\s+/g, '-')
			.trim();
		return slug || `heading-${index}`;
	}

	private setupIntersectionObserver() {
		const contentElement = document.querySelector('app-docs-page');

		const headings = this.getHeadings();

		if (!contentElement) return;

		if (headings.length === 0) {
			this.isVisible.set(false);
			return;
		}

		this.isVisible.set(true);

		let visibleEntries = new Set<string>();

		const observer = new IntersectionObserver(
			(entries) => {
				const visibleHeadings = entries
					.filter(entry => entry.isIntersecting)
					.map(entry => entry.target.id);

				const invisibleHeadings = entries
					.filter(entry => !entry.isIntersecting)
					.map(entry => entry.target.id);


				visibleHeadings.forEach(heading => visibleEntries.add(heading));
				invisibleHeadings.forEach(heading => visibleEntries.delete(heading));

				if (visibleEntries.size > 0) {
					this.activeIds.set([Array.from(visibleEntries)[0]]);
				}
			},
			{
				root: contentElement,
				rootMargin: '-40% 0px -40% 0px',
				threshold: 0
			}
		);

		headings.forEach(heading => observer.observe(heading));
	}

	protected scrollToHeading(id: string) {
		const element = document.getElementById(id);
		if (!element) return

		element.scrollIntoView({
			behavior: 'smooth',
			block: 'center'
		});
	}

	protected isActive(id: string): boolean {
		return this.activeIds().includes(id);
	}

	protected hasChildren(item: TocItem): boolean {
		return item.children.length > 0;
	}
}

@if (isVisible() && hasItems()) {
	<nav class="toc-nav" aria-label="Table of contents">
		<ul class="toc-list">
			@for (item of tocItems(); track item.id) {
				<ng-container
					*ngTemplateOutlet="tocItemTemplate; context: { $implicit: item, level: 1 }"
				/>
			}
		</ul>
	</nav>
}

<ng-template #tocItemTemplate let-item let-level="level">
	<li class="toc-item" [attr.data-level]="level">
		<a
			class="toc-link"
			[class.toc-link--active]="isActive(item.id)"
			[href]="'#' + item.id"
			[class.last]="!hasChildren(item)"
			(click)="scrollToHeading(item.id); $event.preventDefault()"
			[attr.aria-current]="isActive(item.id) ? 'location' : null"
		>
			{{ item.text }}
		</a>

		@if (hasChildren(item)) {
			<ul class="toc-sublist">
				@for (child of item.children; track child.id) {
					<ng-container
						*ngTemplateOutlet="tocItemTemplate; context: { $implicit: child, level: level + 1 }"
					/>
				}
			</ul>
		}
	</li>
</ng-template>

// docs/blocks/core/TableOfContents/TableOfContents.tsx
import { useEffect, useState, memo, useRef } from 'react';
import './TableOfContents.css';

interface TitleTree {
	name: string;
	id: string;
	children: TitleTree[];
}

const buildTitleTree = (titles: {title: string; id: string; level: number}[]): TitleTree[] => {
	if (titles.length === 0) return [];

	const result: TitleTree[] = [];
	const stack: {node: TitleTree; level: number}[] = [];

	for (let index = 0; index < titles.length; index++) {
		const currentTitle = titles[index];
		const newNode: TitleTree = {
			name: currentTitle.title,
			id: currentTitle.id,
			children: []
		};

		while (stack.length > 0 && stack[stack.length - 1].level >= currentTitle.level) {
			stack.pop();
		}

		if (stack.length === 0) {
			result.push(newNode);
		} else {
			stack[stack.length - 1].node.children.push(newNode);
		}

		stack.push({node: newNode, level: currentTitle.level});
	}

	return result;
};

const TableOfContentsTree = memo(({titles, activeId}: {titles: TitleTree[]; activeId: string | null}) => {
	if (titles.length === 0) return null;

	return (
		<ul>
			{titles.map((title) => (
				<TableOfContentsItem
					key={title.id}
					title={title}
					activeId={activeId}
				/>
			))}
		</ul>
	);
});

TableOfContentsTree.displayName = 'TableOfContentsTree';

const TableOfContentsItem = memo(({title, activeId}: {title: TitleTree; activeId: string | null}) => {
	const isActive = title.id === activeId;

	const handleClick = (event: React.MouseEvent<HTMLAnchorElement>) => {
		event.preventDefault();
		const element = document.getElementById(title.id);
		if (element) {
			element.scrollIntoView({
				behavior: 'smooth',
				block: 'center'
			});
			window.history.pushState(null, '', `#${title.id}`);
		}
	};

	return (
		<li>
			<a
				href={`#${title.id}`}
				onClick={handleClick}
				className={isActive ? 'active' : ''}
			>
				{title.name}
			</a>
			{title.children.length > 0 && (
				<TableOfContentsTree titles={title.children} activeId={activeId} />
			)}
		</li>
	);
});

TableOfContentsItem.displayName = 'TableOfContentsItem';

export const TableOfContents = () => {
	const [titlesTree, setTitlesTree] = useState<TitleTree[]>([]);
	const [activeId, setActiveId] = useState<string | null>(null);
	const hasProcessed = useRef(false);
	const observerRef = useRef<IntersectionObserver | null>(null);

	useEffect(() => {
		if (hasProcessed.current) return;

		hasProcessed.current = true;

		const timeoutId = setTimeout(() => {
			const titlesList = document.querySelectorAll('h1,h2,h3,h4,h5,h6');
			const withLevels: {title: string; id: string; level: number}[] = [];

			titlesList.forEach((element) => {
				const title = element.textContent?.trim();
				const id = element.id;
				const levelText = element.nodeName[1];

				if (!title || !id) return;

				const level = +levelText;
				if (isNaN(level)) return;

				withLevels.push({title, id, level});
			});

			const tree = buildTitleTree(withLevels);
			setTitlesTree(tree);
		}, 100);

		return () => clearTimeout(timeoutId);
	}, []);

	useEffect(() => {
		const headingElements = Array.from(
			document.querySelectorAll('h1[id],h2[id],h3[id],h4[id],h5[id],h6[id]')
		);

		if (headingElements.length === 0) return;

		const handleObserver = (entries: IntersectionObserverEntry[]) => {
			const visibleEntries = entries.filter(entry => entry.isIntersecting);

			if (visibleEntries.length > 0) {
				const topVisibleEntry = visibleEntries.reduce((top, entry) => {
					return entry.boundingClientRect.top < top.boundingClientRect.top ? entry : top;
				});

				setActiveId(topVisibleEntry.target.id);
			}
		};

		observerRef.current = new IntersectionObserver(handleObserver, {
			rootMargin: '-40% 0px -40% 0px',
			threshold: [0, 0.25, 0.5, 0.75, 1]
		});

		headingElements.forEach(element => {
			observerRef.current?.observe(element);
		});

		return () => {
			observerRef.current?.disconnect();
		};
	}, [titlesTree]);

	return (
		<div className="fkt-storybook-toc-container">
			<h1 className="fkt-sr-only">Table of contents</h1>
			<TableOfContentsTree titles={titlesTree} activeId={activeId} />
		</div>
	);
};
